CREATE TABLE SYSTEM."CHECK_CODES"
       ("CODE_CATEGORY" CHAR(4) NOT NULL,
       "CODE_VALUE" CHAR(6) NOT NULL,
       "CODE_DISPLAY" VARCHAR(50) NOT NULL,
       "ACCT_BALANCE" NUMBER(7,2) NOT NULL,
       "ACCT_NUMBER" VARCHAR(30));
 
 
ALTER TABLE SYSTEM."CHECK_CODES" ADD ( CONSTRAINT CCKEY1 PRIMARY KEY (
       "CODE_VALUE"
       ));
 

INSERT INTO SYSTEM.pbcattbl(
        pbt_tnam,
        pbt_ownr,
        pbd_fhgt,
        pbd_fwgt,
        pbd_fitl,
        pbd_funl,
        pbd_fchr,
        pbd_fptc,
        pbd_ffce,
        pbh_fhgt,
        pbh_fwgt,
        pbh_fitl,
        pbh_funl,
        pbh_fchr,
        pbh_fptc,
        pbh_ffce,
        pbl_fhgt,
        pbl_fwgt,
        pbl_fitl,
        pbl_funl,
        pbl_fchr,
        pbl_fptc,
        pbl_ffce,
        pbt_cmnt)
        VALUES
       ('CHECK_CODES',
        'SYSTEM',
        -9,
        700,
        'N',
        'N',
        0,
        34,
       'Arial',
        -9,
        400,
        'N',
        'N',
        0,
        34,
       'Arial',
        -9,
        400,
        'N',
        'N',
        0,
        34,
       'Arial',
       'Contains account definitions and other code values used by the CashTrack Sample Application');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_CODES',
        'SYSTEM',
        'CODE_CATEGORY',
        'Code Category:',
        23,
        'Code Category',
        25,
        23,
        '',
        26,
        61,
        526,
        '',
        'N',
        '',
       'codes',
       'A code value that identifies the type of code');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_CODES',
        'SYSTEM',
        'CODE_VALUE',
        'Code Value:',
        23,
        'Code Value',
        25,
        23,
        '',
        26,
        61,
        330,
        '',
        'N',
        '',
       '',
       'A unique code for the category');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_CODES',
        'SYSTEM',
        'CODE_DISPLAY',
        'Code Display:',
        23,
        'Code Display',
        25,
        23,
        '',
        26,
        61,
        878,
        '',
        'N',
        '',
       '',
       'The display value of the code definition');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_CODES',
        'SYSTEM',
        'ACCT_BALANCE',
        'Acct Balance:',
        23,
        'Acct Balance',
        25,
        24,
        'dollars',
        26,
        61,
        394,
        '',
        'N',
        '0',
       'dollars',
       'The account starting balance');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_CODES',
        'SYSTEM',
        'ACCT_NUMBER',
        'Acct Number:',
        23,
        'Acct Number',
        25,
        23,
        '',
        26,
        61,
        439,
        '',
        'N',
        '',
       '',
       'The account''s account number');
 
COMMIT WORK;
 
CREATE TABLE SYSTEM."CHECK_DETAIL"
       ("ACCOUNT_CODE" CHAR(6) NOT NULL,
       "BALANCE_TYPE" CHAR(1) NOT NULL,
       "EXP_CATEGORY1" CHAR(6) NOT NULL,
       "EXP_CATEGORY2" CHAR(6) NOT NULL,
       "POSTING_DATE" DATE NOT NULL,
       "CHECK_NUMBER" CHAR(5) NOT NULL,
       "TRANS_NUMBER" CHAR(5) NOT NULL,
       "DESCRIPTION" CHAR(50) NOT NULL,
       "TRANS_AMOUNT" NUMBER(7,2) NOT NULL,
       "EXP_AMOUNT" NUMBER(7,2) NOT NULL,
       "MEMO_FLD" VARCHAR(40),
       "POST_TYPE" CHAR(1) NOT NULL,
       "TAX_EXEMPT" CHAR(1) NOT NULL);
 
 
ALTER TABLE SYSTEM."CHECK_DETAIL" ADD ( CONSTRAINT CDKEY1 PRIMARY KEY (
       "ACCOUNT_CODE",
       "POSTING_DATE",
       "CHECK_NUMBER",
       "TRANS_NUMBER",
       "DESCRIPTION",
       "TRANS_AMOUNT"
       ));
 
ALTER TABLE SYSTEM."CHECK_DETAIL" ADD ( CONSTRAINT FCODES1 FOREIGN KEY  (
       "ACCOUNT_CODE"
       ) REFERENCES system."CHECK_CODES"
        );
 
 

INSERT INTO SYSTEM.pbcattbl(
        pbt_tnam,
        pbt_ownr,
        pbd_fhgt,
        pbd_fwgt,
        pbd_fitl,
        pbd_funl,
        pbd_fchr,
        pbd_fptc,
        pbd_ffce,
        pbh_fhgt,
        pbh_fwgt,
        pbh_fitl,
        pbh_funl,
        pbh_fchr,
        pbh_fptc,
        pbh_ffce,
        pbl_fhgt,
        pbl_fwgt,
        pbl_fitl,
        pbl_funl,
        pbl_fchr,
        pbl_fptc,
        pbl_ffce,
        pbt_cmnt)
        VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        -9,
        700,
        'N',
        'N',
        0,
        34,
       'Arial',
        -9,
        400,
        'N',
        'N',
        0,
        34,
       'Arial',
        -9,
        400,
        'N',
        'N',
        0,
        34,
       'Arial',
       'This table contains detail entries for the CashTrack Sample Application');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'ACCOUNT_CODE',
        'Acct. Code',
        0,
        'Acct.~r~nCode',
        0,
        0,
        '',
        0,
        61,
        572,
        '',
        'N',
        'null',
       'acct_edit',
       'The code that identifies this account');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'BALANCE_TYPE',
        'Clear?',
        0,
        'Clear?',
        0,
        25,
        '',
        0,
        61,
        69,
        '',
        'N',
        'N',
       'clear_cbx',
       'An indicator if the item has cleared the bank');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'EXP_CATEGORY1',
        'Exp. Category',
        0,
        'Expense~r~nCategory',
        0,
        0,
        '',
        0,
        61,
        439,
        '',
        'N',
        'X',
       'exp_cat1_edit',
       'A major category of expense (Used for Analysis)');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'EXP_CATEGORY2',
        'Sub-Cat:',
        0,
        'Sub~r~nCategory',
        0,
        0,
        '',
        0,
        61,
        439,
        '',
        'N',
        'XX',
       'exp_cat2_edit',
       'A sub-category of expense (Used for Analysis)');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'POSTING_DATE',
        'Post Date',
        0,
        'Posting~r~nDate',
        0,
        0,
        '',
        0,
        61,
        220,
        '',
        'N',
        'today',
       'MM/DD/YY',
       'The date the item was posted');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'CHECK_NUMBER',
        'Check #',
        0,
        'Check~r~nNumber',
        0,
        25,
        '',
        0,
        61,
        69,
        '',
        'N',
        'spaces',
       '',
       'The check number of the item');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'TRANS_NUMBER',
        'Trans. #:',
        0,
        'Trans.~r~nNumber',
        0,
        25,
        '',
        0,
        61,
        69,
        '',
        'N',
        'spaces',
       '',
       'A transaction number for the item.');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'DESCRIPTION',
        'Description',
        0,
        'Description',
        0,
        0,
        '',
        0,
        61,
        878,
        '',
        'N',
        '',
       'Payees',
       'A description of the item or activity.');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'TRANS_AMOUNT',
        'Amt:',
        0,
        'Amount',
        0,
        0,
        'dollars',
        0,
        61,
        330,
        '',
        'N',
        '0',
       'dollars',
       'The amount of the transaction');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'EXP_AMOUNT',
        'Exp. Amt.',
        0,
        'Expense~r~nAmount',
        0,
        0,
        'dollars',
        0,
        61,
        330,
        '',
        'N',
        '0',
       'dollars',
       'The amount to be used for Expense Amount (usually absolute value of trans_amount)');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'MEMO_FLD',
        'Memo:',
        23,
        'Memo',
        25,
        23,
        '',
        26,
        61,
        220,
        '',
        'N',
        '',
       '',
       'Memo text associated with the item or activity.');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'POST_TYPE',
        'Post Type:',
        23,
        'Post~r~nType',
        25,
        23,
        '',
        26,
        61,
        330,
        '',
        'N',
        'C',
       'act_type',
       'A code identifying the item as a Check (C), Deposit (D), Withdrawal (W) or Payment (P)');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_DETAIL',
        'SYSTEM',
        'TAX_EXEMPT',
        'Tax Exempt:',
        23,
        'Tax~r~nExempt',
        25,
        23,
        '',
        26,
        61,
        110,
        '',
        'N',
        'N',
       'clear_cbx',
       'A code to determine if the expense is Tax-Deductible');
 
COMMIT WORK;
 
CREATE TABLE SYSTEM."CHECK_HISTORY"
       ("ACCOUNT_CODE" CHAR(6) NOT NULL,
       "BALANCE_TYPE" CHAR(1) NOT NULL,
       "EXP_CATEGORY1" CHAR(6) NOT NULL,
       "EXP_CATEGORY2" CHAR(6) NOT NULL,
       "POSTING_DATE" DATE NOT NULL,
       "CHECK_NUMBER" CHAR(5) NOT NULL,
       "TRANS_NUMBER" CHAR(5) NOT NULL,
       "DESCRIPTION" CHAR(50) NOT NULL,
       "TRANS_AMOUNT" NUMBER(7,2) NOT NULL,
       "EXP_AMOUNT" NUMBER(7,2) NOT NULL,
       "MEMO_FLD" VARCHAR(40),
       "POST_TYPE" CHAR(1) NOT NULL,
       "TAX_EXEMPT" CHAR(1) NOT NULL);
 
 
ALTER TABLE SYSTEM."CHECK_HISTORY" ADD ( CONSTRAINT CHKEY1 PRIMARY KEY (
       "ACCOUNT_CODE",
       "POSTING_DATE",
       "CHECK_NUMBER",
       "TRANS_NUMBER",
       "DESCRIPTION",
       "TRANS_AMOUNT"
       ));
 
 
INSERT INTO SYSTEM.pbcattbl(
        pbt_tnam,
        pbt_ownr,
        pbd_fhgt,
        pbd_fwgt,
        pbd_fitl,
        pbd_funl,
        pbd_fchr,
        pbd_fptc,
        pbd_ffce,
        pbh_fhgt,
        pbh_fwgt,
        pbh_fitl,
        pbh_funl,
        pbh_fchr,
        pbh_fptc,
        pbh_ffce,
        pbl_fhgt,
        pbl_fwgt,
        pbl_fitl,
        pbl_funl,
        pbl_fchr,
        pbl_fptc,
        pbl_ffce,
        pbt_cmnt)
        VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        -9,
        700,
        'N',
        'N',
        0,
        34,
       'Arial',
        -9,
        400,
        'N',
        'N',
        0,
        34,
       'Arial',
        -9,
        400,
        'N',
        'N',
        0,
        34,
       'Arial',
       'Items purged from check_detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'ACCOUNT_CODE',
        'Acct. Code',
        0,
        'Acct.~r~nCode',
        0,
        0,
        '',
        0,
        61,
        572,
        '',
        'N',
        'null',
       'acct_edit',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'BALANCE_TYPE',
        'Clear?',
        0,
        'Clear?',
        0,
        25,
        '',
        0,
        61,
        69,
        '',
        'N',
        'N',
       'clear_cbx',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'EXP_CATEGORY1',
        'Exp. Category',
        0,
        'Expense~r~nCategory',
        0,
        0,
        '',
        0,
        61,
        439,
        '',
        'N',
        'X',
       'exp_cat1_edit',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'EXP_CATEGORY2',
        'Sub-Cat:',
        0,
        'Sub~r~nCategory',
        0,
        0,
        '',
        0,
        61,
        439,
        '',
        'N',
        'XX',
       'exp_cat2_edit',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'POSTING_DATE',
        'Post Date',
        0,
        'Posting~r~nDate',
        0,
        0,
        '',
        0,
        61,
        220,
        '',
        'N',
        'today',
       'MM/DD/YY',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'CHECK_NUMBER',
        'Check #',
        0,
        'Check~r~nNumber',
        0,
        25,
        '',
        0,
        61,
        69,
        '',
        'N',
        '',
       '',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'TRANS_NUMBER',
        'Trans. #:',
        0,
        'Trans.~r~nNumber',
        0,
        25,
        '',
        0,
        61,
        69,
        '',
        'N',
        '',
       '',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'DESCRIPTION',
        'Description',
        0,
        'Description',
        0,
        0,
        '',
        0,
        61,
        878,
        '',
        'N',
        '',
       'Payees',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'TRANS_AMOUNT',
        'Amt:',
        0,
        'Amount',
        0,
        0,
        'dollars',
        0,
        61,
        330,
        '',
        'N',
        '0',
       'dollars',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'EXP_AMOUNT',
        'Exp. Amt.',
        0,
        'Expense~r~nAmount',
        0,
        0,
        'dollars',
        0,
        61,
        69,
        '',
        'N',
        '0',
       'dollars',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'MEMO_FLD',
        'Memo:',
        23,
        'Memo',
        25,
        23,
        '',
        26,
        61,
        220,
        '',
        'N',
        '',
       '',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'POST_TYPE',
        'Post Type:',
        23,
        'Post~r~nType',
        25,
        23,
        '',
        26,
        61,
        330,
        '',
        'N',
        'C',
       'act_type',
       'Same as Check Detail table');
 
INSERT INTO SYSTEM.pbcatcol(
       pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_edit,
       pbc_cmnt
       )VALUES
       ('CHECK_HISTORY',
        'SYSTEM',
        'TAX_EXEMPT',
        'Tax Exempt:',
        23,
        'Tax~r~nExempt',
        25,
        23,
        '',
        26,
        61,
        110,
        '',
        'N',
        'N',
       'clear_cbx',
       'Same as Check Detail table');
 
COMMIT WORK;

CREATE TABLE SYSTEM."CHECK_BUDGET"
       ("EXP_CATEGORY1" CHAR(10) NOT NULL,
       "EXP_CATEGORY2" CHAR(10) NOT NULL,
       "MONTH" NUMBER(2,0) NOT NULL,
       "YEAR" NUMBER (4,0) NOT NULL,
       "MONTH_BUDGET" NUMBER(7,2) NOT NULL,
       "YEAR_BUDGET" NUMBER(7,2) NOT NULL);

ALTER TABLE SYSTEM."CHECK_BUDGET" ADD ( CONSTRAINT CCKEY5 PRIMARY KEY (
       "EXP_CATEGORY1",
       "MONTH",
       "YEAR"
       ));

INSERT INTO SYSTEM.pbcattbl
        (pbt_tnam,
       pbt_ownr,
       pbd_fhgt,
       pbd_fwgt,
       pbd_fitl,
       pbd_funl,
       pbd_fchr,
       pbd_fptc,
       pbd_ffce,
       pbh_fhgt,
       pbh_fwgt,
       pbh_fitl,
       pbh_funl,
       pbh_fchr,
       pbh_fptc,
       pbh_ffce,
       pbl_fhgt,
       pbl_fwgt,
       pbl_fitl,
       pbl_funl,
       pbl_fchr,
       pbl_fptc,
       pbl_ffce,
       pbt_cmnt)
       VALUES
        ( 'CHECK_BUDGET',
        'SYSTEM',
        -8,
        400,
        'N',
        'N',
        0,
        0,
        '',
        -8,
        700,
        'N',
        'N',
        0,
        0,
        '',
        -8,
        700 ,
        'N',
        'N',
        0,
        0,
        '',
       'Budget Information');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_BUDGET',
        'SYSTEM',
        'exp_category1',
       1,
        'Exp Category1:',
       0 ,
        'Expense
Category1',
       0,
       23 ,
        '',
       0 ,
       61 ,
       549 ,
        '',
       'N',
        'X',
        'The Major Expense Category for budget item',
        'exp1_dddw',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_BUDGET',
        'SYSTEM',
        'exp_category2',
       2,
        'Exp Category2:',
       0 ,
        'Expense
Category2',
       0,
       23 ,
        '',
       0 ,
       61 ,
       549 ,
        '',
       'N',
        'XX',
        'The Minor Expense Category for the budget item',
        'exp2_dddw',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_BUDGET',
        'SYSTEM',
        'month',
       3,
        'Month:',
       23 ,
        'Month',
       25,
       24 ,
        '',
       0 ,
       61 ,
       275 ,
        '',
       'N',
        '01',
        'The month of the budget item',
        '##',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_BUDGET',
        'SYSTEM',
        'year',
       4,
        'Year:',
       23 ,
        'Year',
       25,
       24 ,
        '',
       0 ,
       61 ,
       275 ,
        '',
       'N',
        '0',
        'The year of the budget item',
        '',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_BUDGET',
        'SYSTEM',
        'month_budget',
       5,
        'Month Budget:',
       23 ,
        'Month Budget',
       25,
       24 ,
        'currency_display',
       0 ,
       61 ,
       275 ,
        '',
       'N',
        '0',
        'The budgeted amount per month',
        '',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_BUDGET',
        'SYSTEM',
        'year_budget',
       6,
        'Year Budget:',
       23 ,
        'Year Budget',
       25,
       24 ,
        'currency_display',
       0 ,
       61 ,
       275 ,
        '',
       'N',
        '0',
        'The budgeted amount per year',
        '',
       '');
 

CREATE TABLE SYSTEM."CHECK_RECURRING"
       ("ACCOUNT_CODE" char(6) NOT NULL,
       "EXP_CATEGORY1" char(6) NOT NULL,
       "EXP_CATEGORY2" char(6) NOT NULL,
       "LAST_POSTING_DATE" date,
       "FREQUENCY" char(1) NOT NULL,
       "PAY_DATE1" char(5) NOT NULL,
       "PAY_DATE2" char(5) ,
       "DESCRIPTION" char(50) NOT NULL,
       "TRANS_AMOUNT" number(7,2) NOT NULL,
       "MEMO_FLD" varchar(40) ,
       "POST_TYPE" char(1) NOT NULL,
       "TAX_EXEMPT" char(1) NOT NULL,
       "NOTIFICATION_DAYS" number(2,0) );
 
ALTER TABLE SYSTEM."CHECK_RECURRING" 
ADD ( CONSTRAINT CCKEY6 PRIMARY KEY (
       "ACCOUNT_CODE",
       "DESCRIPTION",
       "TRANS_AMOUNT"
       ));
 
INSERT INTO SYSTEM.pbcattbl
        (pbt_tnam,
       pbt_ownr,
       pbd_fhgt,
       pbd_fwgt,
       pbd_fitl,
       pbd_funl,
       pbd_fchr,
       pbd_fptc,
       pbd_ffce,
       pbh_fhgt,
       pbh_fwgt,
       pbh_fitl,
       pbh_funl,
       pbh_fchr,
       pbh_fptc,
       pbh_ffce,
       pbl_fhgt,
       pbl_fwgt,
       pbl_fitl,
       pbl_funl,
       pbl_fchr,
       pbl_fptc,
       pbl_ffce,
       pbt_cmnt)
       VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        -8,
        400,
        'N',
        'N',
        0,
        0,
        '',
        -8,
        700,
        'N',
        'N',
        0,
        0,
        '',
        -8,
        700 ,
        'N',
        'N',
        0,
        0,
        '',
       'This table contains information about recurring activities');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'account_code',
       1,
        'Account:',
       0 ,
        'Acct.
Code',
       0,
       23 ,
        '',
       0 ,
       61 ,
       636 ,
        '',
       'N',
        'spaces',
        'The code that identifies this account',
        'acct_dddw',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'exp_category1',
       2,
        'Exp Category1:',
       0 ,
        'Expense~r~nCategory1',
       0,
       23 ,
        '',
       0 ,
       61 ,
       540 ,
        '',
       'N',
        'spaces',
        'A major category of expense',
        'exp1_dddw',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'exp_category2',
       3,
        'Exp Category2:',
       0 ,
        'Expense~r~nCategory2',
       0,
       23 ,
        '',
       0 ,
       61 ,
       540 ,
        '',
       'N',
        'spaces',
        'A sub-category of expense',
        'exp2_dddw',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'last_posting_date',
       4,
        'Last:',
       23 ,
        'Last~r~nPosting',
       25,
       25 ,
        '',
       0 ,
       61 ,
       266 ,
        '',
       'N',
        'null',
        'The date of the last posting',
        'MM/DD/YY',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'frequency',
       5,
        'Freq:',
       23 ,
        'Frequency',
       25,
       23 ,
        '',
       0 ,
       61 ,
       133 ,
        '',
       'N',
        'M',
        'A frequency of payment: 1/month, bi-monthly, etc.',
        'pay_freq_edit',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'pay_date1',
       6,
        'Day to Pay:',
       23 ,
        'Day to Pay',
       25,
       23 ,
        '',
       0 ,
       61 ,
       133 ,
        '',
       'N',
        '01',
        'The day of the month when payment is due',
        '##',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'pay_date2',
       7,
        'Day:',
       23 ,
        'Day to Pay',
       25,
       23 ,
        '',
       0 ,
       61 ,
       133 ,
        '',
       'N',
        '15',
        'The day of the month when payment is due',
        '##',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'description',
       8,
        'Description:',
       0 ,
        'Description',
       0,
       23 ,
        '',
       0 ,
       61 ,
       659 ,
        '',
       'N',
        'spaces',
        'A description of the item or activity',
        'payees',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'trans_amount',
       9,
        'Amt:',
       0 ,
        'Amount',
       0,
       24 ,
        'currency_display',
       0 ,
       61 ,
       307 ,
        '',
       'N',
        '0',
        'The amount of the payment.',
        '',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'memo_fld',
       10,
        'Memo:',
       23 ,
        'Memo',
       25,
       23 ,
        '',
       0 ,
       61 ,
       439 ,
        '',
       'N',
        'null',
        'A memo field',
        '',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'post_type',
       11,
        'Post Type:',
       0 ,
        'Post
Type',
       0,
       23 ,
        '',
       0 ,
       61 ,
       220 ,
        '',
       'N',
        'C',
        'A code identifying the activity as a check, deposit, withdraw or payment',
        'type_ddlb',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'tax_exempt',
       12,
        'Tax Exempt:',
       0 ,
        'Tax~r~nExempt',
       0,
       25 ,
        '',
       26 ,
       61 ,
       133 ,
        '',
       'N',
        'N',
        'Code identifies whether activity is tax exempt.',
        'yes_no',
       '');
 
INSERT INTO SYSTEM.pbcatcol
       (pbc_tnam,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'CHECK_RECURRING',
        'SYSTEM',
        'notification_days',
       13,
        'Notification Days:',
       23 ,
        'Notification Days',
       25,
       24 ,
        '',
       26 ,
       61 ,
       133 ,
        '',
       'N',
        '0',
        'The number of days before and after to notify that payment is due',
        '##',
       '');