CREATE TABLE dbo.check_history
       (account_code char(6) NOT NULL,
       balance_type char(1) NOT NULL,
       exp_category1 char(6) NOT NULL,
       exp_category2 char(6) NOT NULL,
       posting_date datetime NOT NULL,
       check_number char(5) NOT NULL,
       trans_number char(5) NOT NULL,
       description char(50) NOT NULL,
       trans_amount money NOT NULL,
       exp_amount money NOT NULL,
       memo_fld varchar(40) NULL,
       post_type char(1) NOT NULL,
       tax_exempt char(1) NOT NULL);
 
ALTER TABLE check_history
       ADD CONSTRAINT cthist_x PRIMARY KEY
       (account_code,posting_date,check_number,trans_number,description,trans_amount) ;

INSERT INTO dbo.pbcattbl
        (pbt_tnam,
       pbt_tid,
       pbt_ownr,
       pbd_fhgt,
       pbd_fwgt,
       pbd_fitl,
       pbd_funl,
       pbd_fchr,
       pbd_fptc,
       pbd_ffce,
       pbh_fhgt,
       pbh_fwgt,
       pbh_fitl,
       pbh_funl,
       pbh_fchr,
       pbh_fptc,
       pbh_ffce,
       pbl_fhgt,
       pbl_fwgt,
       pbl_fitl,
       pbl_funl,
       pbl_fchr,
       pbl_fptc,
       pbl_ffce,
       pbt_cmnt)
       VALUES
        ( 'check_history',
       OBJECT_ID("dbo.check_history"),
        'dbo',
        -9,
        700,
        'N',
        'N',
        0,
        34,
        'Arial',
        -9,
        400,
        'N',
        'N',
        0,
        34,
        'Arial',
        -9,
        400 ,
        'N',
        'N',
        0,
        34,
        'Arial',
       'Items purged from check_detail table');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'account_code',
       1,
        'Acct. Code',
       0 ,
        'Acct.~r~nCode',
       0,
       0 ,
        '',
       0 ,
       61 ,
       572 ,
        '',
       'N',
        'null',
        'Same as Check Detail table',
        'acct_edit',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'balance_type',
       2,
        'Clear?',
       0 ,
        'Clear?',
       0,
       25 ,
        '',
       0 ,
       61 ,
       69 ,
        '',
       'N',
        'N',
        'Same as Check Detail table',
        'clear_cbx',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'exp_category1',
       3,
        'Exp. Category',
       0 ,
        'Expense~r~nCategory',
       0,
       0 ,
        '',
       0 ,
       61 ,
       439 ,
        '',
       'N',
        'X',
        'Same as Check Detail table',
        'exp_cat1_edit',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'exp_category2',
       4,
        'Sub-Cat:',
       0 ,
        'Sub~r~nCategory',
       0,
       0 ,
        '',
       0 ,
       61 ,
       439 ,
        '',
       'N',
        'XX',
        'Same as Check Detail table',
        'exp_cat2_edit',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'posting_date',
       5,
        'Post Date',
       0 ,
        'Posting~r~nDate',
       0,
       0 ,
        '',
       0 ,
       61 ,
       220 ,
        '',
       'N',
        'today',
        'Same as Check Detail table',
        'MM/DD/YY',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'check_number',
       6,
        'Check #',
       0 ,
        'Check~r~nNumber',
       0,
       25 ,
        '',
       0 ,
       61 ,
       69 ,
        '',
       'N',
        '',
        'Same as Check Detail table',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'trans_number',
       7,
        'Trans. #:',
       0 ,
        'Trans.~r~nNumber',
       0,
       25 ,
        '',
       0 ,
       61 ,
       69 ,
        '',
       'N',
        '',
        'Same as Check Detail table',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'description',
       8,
        'Description',
       0 ,
        'Description',
       0,
       0 ,
        '',
       0 ,
       61 ,
       878 ,
        '',
       'N',
        '',
        'Same as Check Detail table',
        'Payees',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'trans_amount',
       9,
        'Amt:',
       0 ,
        'Amount',
       0,
       0 ,
        'dollars',
       0 ,
       61 ,
       330 ,
        '',
       'N',
        '0',
        'Same as Check Detail table',
        'dollars',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'exp_amount',
       10,
        'Exp. Amt.',
       0 ,
        'Expense~r~nAmount',
       0,
       0 ,
        'dollars',
       0 ,
       61 ,
       69 ,
        '',
       'N',
        '0',
        'Same as Check Detail table',
        'dollars',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'memo_fld',
       11,
        'Memo:',
       23 ,
        'Memo',
       25,
       23 ,
        '',
       26 ,
       61 ,
       220 ,
        '',
       'N',
        '',
        'Same as Check Detail table',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'post_type',
       12,
        'Post Type:',
       23 ,
        'Post~r~nType',
       25,
       23 ,
        '',
       26 ,
       61 ,
       330 ,
        '',
       'N',
        'C',
        'Same as Check Detail table',
        'act_type',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_history',
        OBJECT_ID("dbo.check_history"),
        'dbo',
        'tax_exempt',
       13,
        'Tax Exempt:',
       23 ,
        'Tax~r~nExempt',
       25,
       23 ,
        '',
       26 ,
       61 ,
       110 ,
        '',
       'N',
        'N',
        'Same as Check Detail table',
        'clear_cbx',
       '');
 
CREATE TABLE dbo.check_codes
       (code_category char(4) NOT NULL,
       code_value char(6) NOT NULL,
       code_display varchar(50) NOT NULL,
       acct_balance money NOT NULL,
       acct_number varchar(30) NULL);
 
ALTER TABLE check_codes
       ADD CONSTRAINT ctcodes_x PRIMARY KEY
       (code_value)
 
INSERT INTO dbo.pbcattbl
        (pbt_tnam,
       pbt_tid,
       pbt_ownr,
       pbd_fhgt,
       pbd_fwgt,
       pbd_fitl,
       pbd_funl,
       pbd_fchr,
       pbd_fptc,
       pbd_ffce,
       pbh_fhgt,
       pbh_fwgt,
       pbh_fitl,
       pbh_funl,
       pbh_fchr,
       pbh_fptc,
       pbh_ffce,
       pbl_fhgt,
       pbl_fwgt,
       pbl_fitl,
       pbl_funl,
       pbl_fchr,
       pbl_fptc,
       pbl_ffce,
       pbt_cmnt)
       VALUES
        ( 'check_codes',
       OBJECT_ID("dbo.check_codes"),
        'dbo',
        -9,
        700,
        'N',
        'N',
        0,
        34,
        'Arial',
        -9,
        400,
        'N',
        'N',
        0,
        34,
        'Arial',
        -9,
        400 ,
        'N',
        'N',
        0,
        34,
        'Arial',
       'Contains account definitions and other code values used by the CashTrack Sample Application');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_codes',
        OBJECT_ID("dbo.check_codes"),
        'dbo',
        'code_category',
       1,
        'Code Category:',
       23 ,
        'Code Category',
       25,
       23 ,
        '',
       26 ,
       61 ,
       526 ,
        '',
       'N',
        '',
        'A code value that identifies the type of code',
        'codes',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_codes',
        OBJECT_ID("dbo.check_codes"),
        'dbo',
        'code_value',
       2,
        'Code Value:',
       23 ,
        'Code Value',
       25,
       23 ,
        '',
       26 ,
       61 ,
       330 ,
        '',
       'N',
        '',
        'A unique code for the category',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_codes',
        OBJECT_ID("dbo.check_codes"),
        'dbo',
        'code_display',
       3,
        'Code Display:',
       23 ,
        'Code Display',
       25,
       23 ,
        '',
       26 ,
       61 ,
       878 ,
        '',
       'N',
        '',
        'The display value of the code definition',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_codes',
        OBJECT_ID("dbo.check_codes"),
        'dbo',
        'acct_balance',
       4,
        'Acct Balance:',
       23 ,
        'Acct Balance',
       25,
       24 ,
        'dollars',
       26 ,
       61 ,
       394 ,
        '',
       'N',
        '0',
        'The account starting balance',
        'dollars',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_codes',
        OBJECT_ID("dbo.check_codes"),
        'dbo',
        'acct_number',
       5,
        'Acct Number:',
       23 ,
        'Acct Number',
       25,
       23 ,
        '',
       26 ,
       61 ,
       439 ,
        '',
       'N',
        '',
        'The account''s account number',
        '',
       '');
 
CREATE TABLE dbo.check_detail
       (account_code char(6) NOT NULL,
       balance_type char(1) NOT NULL,
       exp_category1 char(6) NOT NULL,
       exp_category2 char(6) NOT NULL,
       posting_date datetime NOT NULL,
       check_number char(5) NOT NULL,
       trans_number char(5) NOT NULL,
       description char(50) NOT NULL,
       trans_amount money NOT NULL,
       exp_amount money NOT NULL,
       memo_fld varchar(40) NULL,
       post_type char(1) NOT NULL,
       tax_exempt char(1) NOT NULL);
 

ALTER TABLE check_detail
       ADD CONSTRAINT ctdet_x PRIMARY KEY
       (account_code,posting_date,check_number,trans_number,description,trans_amount) ;

 
INSERT INTO dbo.pbcattbl
        (pbt_tnam,
       pbt_tid,
       pbt_ownr,
       pbd_fhgt,
       pbd_fwgt,
       pbd_fitl,
       pbd_funl,
       pbd_fchr,
       pbd_fptc,
       pbd_ffce,
       pbh_fhgt,
       pbh_fwgt,
       pbh_fitl,
       pbh_funl,
       pbh_fchr,
       pbh_fptc,
       pbh_ffce,
       pbl_fhgt,
       pbl_fwgt,
       pbl_fitl,
       pbl_funl,
       pbl_fchr,
       pbl_fptc,
       pbl_ffce,
       pbt_cmnt)
       VALUES
        ( 'check_detail',
       OBJECT_ID("dbo.check_detail"),
        'dbo',
        -9,
        700,
        'N',
        'N',
        0,
        34,
        'Arial',
        -9,
        400,
        'N',
        'N',
        0,
        34,
        'Arial',
        -9,
        400 ,
        'N',
        'N',
        0,
        34,
        'Arial',
       'This table contains detail entries for the CashTrack Sample Application');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'account_code',
       1,
        'Acct. Code',
       0 ,
        'Acct.~r~nCode',
       0,
       0 ,
        '',
       0 ,
       61 ,
       572 ,
        '',
       'N',
        'null',
        'The code that identifies this account',
        'acct_edit',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'balance_type',
       2,
        'Clear?',
       0 ,
        'Clear?',
       0,
       25 ,
        '',
       0 ,
       61 ,
       69 ,
        '',
       'N',
        'N',
        'An indicator if the item has cleared the bank',
        'clear_cbx',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'exp_category1',
       3,
        'Exp. Category',
       0 ,
        'Expense~r~nCategory',
       0,
       0 ,
        '',
       0 ,
       61 ,
       439 ,
        '',
       'N',
        'X',
        'A major category of expense (Used for Analysis)',
        'exp_cat1_edit',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'exp_category2',
       4,
        'Sub-Cat:',
       0 ,
        'Sub~r~nCategory',
       0,
       0 ,
        '',
       0 ,
       61 ,
       439 ,
        '',
       'N',
        'XX',
        'A sub-category of expense (Used for Analysis)',
        'exp_cat2_edit',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'posting_date',
       5,
        'Post Date',
       0 ,
        'Posting~r~nDate',
       0,
       0 ,
        '',
       0 ,
       61 ,
       220 ,
        '',
       'N',
        'today',
        'The date the item was posted',
        'MM/DD/YY',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'check_number',
       6,
        'Check #',
       0 ,
        'Check~r~nNumber',
       0,
       25 ,
        '',
       0 ,
       61 ,
       69 ,
        '',
       'N',
        'spaces',
        'The check number of the item',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'trans_number',
       7,
        'Trans. #:',
       0 ,
        'Trans.~r~nNumber',
       0,
       25 ,
        '',
       0 ,
       61 ,
       69 ,
        '',
       'N',
        'spaces',
        'A transaction number for the item.',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'description',
       8,
        'Description',
       0 ,
        'Description',
       0,
       0 ,
        '',
       0 ,
       61 ,
       878 ,
        '',
       'N',
        '',
        'A description of the item or activity.',
        'Payees',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'trans_amount',
       9,
        'Amt:',
       0 ,
        'Amount',
       0,
       0 ,
        'dollars',
       0 ,
       61 ,
       330 ,
        '',
       'N',
        '0',
        'The amount of the transaction',
        'dollars',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'exp_amount',
       10,
        'Exp. Amt.',
       0 ,
        'Expense~r~nAmount',
       0,
       0 ,
        'dollars',
       0 ,
       61 ,
       330 ,
        '',
       'N',
        '0',
        'The amount to be used for Expense Amount (usually absolute value of trans_amount)',
        'dollars',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'memo_fld',
       11,
        'Memo:',
       23 ,
        'Memo',
       25,
       23 ,
        '',
       26 ,
       61 ,
       220 ,
        '',
       'N',
        '',
        'Memo text associated with the item or activity.',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'post_type',
       12,
        'Post Type:',
       23 ,
        'Post~r~nType',
       25,
       23 ,
        '',
       26 ,
       61 ,
       330 ,
        '',
       'N',
        'C',
        'A code identifying the item as a Check (C), Deposit (D), Withdrawal (W) or Payment (P)',
        'act_type',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_detail',
        OBJECT_ID("dbo.check_detail"),
        'dbo',
        'tax_exempt',
       13,
        'Tax Exempt:',
       23 ,
        'Tax~r~nExempt',
       25,
       23 ,
        '',
       26 ,
       61 ,
       110 ,
        '',
       'N',
        'N',
        'A code to determine if the expense is Tax-Deductible',
        'clear_cbx',
       '');

ALTER TABLE check_detail
       ADD CONSTRAINT ctdet_fx FOREIGN KEY (account_code)
        REFERENCES check_codes (code_value) ;


CREATE TABLE dbo.check_budget
       (exp_category1 char(10) NOT NULL,
       exp_category2 char(10) NULL,
       month int NOT NULL,
       year  int NOT NULL,
       month_budget money NOT NULL,
       year_budget money NOT NULL);
 
ALTER TABLE check_budget
       ADD CONSTRAINT ctbud_x PRIMARY KEY
       (exp_category1,month,year) ;
 
INSERT INTO dbo.pbcattbl
        (pbt_tnam,
       pbt_tid,
       pbt_ownr,
       pbd_fhgt,
       pbd_fwgt,
       pbd_fitl,
       pbd_funl,
       pbd_fchr,
       pbd_fptc,
       pbd_ffce,
       pbh_fhgt,
       pbh_fwgt,
       pbh_fitl,
       pbh_funl,
       pbh_fchr,
       pbh_fptc,
       pbh_ffce,
       pbl_fhgt,
       pbl_fwgt,
       pbl_fitl,
       pbl_funl,
       pbl_fchr,
       pbl_fptc,
       pbl_ffce,
       pbt_cmnt)
       VALUES
        ( 'check_budget',
       OBJECT_ID("dbo.check_budget"),
        'dba',
        -8,
        400,
        'N',
        'N',
        0,
        0,
        '',
        -8,
        700,
        'N',
        'N',
        0,
        0,
        '',
        -8,
        700 ,
        'N',
        'N',
        0,
        0,
        '',
       'Budget Information');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_budget',
        OBJECT_ID("dbo.check_budget"),
        'dba',
        'exp_category1',
       1,
        'Exp Category1:',
       0 ,
        'Expense
Category1',
       0,
       23 ,
        '',
       0 ,
       61 ,
       549 ,
        '',
       'N',
        'X',
        'The Major Expense Category for budget item',
        'exp1_dddw',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_budget',
        OBJECT_ID("dbo.check_budget"),
        'dba',
        'exp_category2',
       2,
        'Exp Category2:',
       0 ,
        'Expense
Category2',
       0,
       23 ,
        '',
       0 ,
       61 ,
       549 ,
        '',
       'N',
        'XX',
        'The Minor Expense Category for the budget item',
        'exp2_dddw',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_budget',
        OBJECT_ID("dbo.check_budget"),
        'dba',
        'month',
       3,
        'Month:',
       23 ,
        'Month',
       25,
       24 ,
        '',
       0 ,
       61 ,
       275 ,
        '',
       'N',
        '01',
        'The month of the budget item',
        '##',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_budget',
        OBJECT_ID("dbo.check_budget"),
        'dba',
        'year',
       4,
        'Year:',
       23 ,
        'Year',
       25,
       24 ,
        '',
       0 ,
       61 ,
       275 ,
        '',
       'N',
        '0',
        'The year of the budget item',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_budget',
        OBJECT_ID("dbo.check_budget"),
        'dba',
        'month_budget',
       5,
        'Month Budget:',
       23 ,
        'Month Budget',
       25,
       24 ,
        'currency_display',
       0 ,
       61 ,
       275 ,
        '',
       'N',
        '0',
        'The budgeted amount per month',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_budget',
        OBJECT_ID("dbo.check_budget"),
        'dba',
        'year_budget',
       6,
        'Year Budget:',
       23 ,
        'Year Budget',
       25,
       24 ,
        'currency_display',
       0 ,
       61 ,
       275 ,
        '',
       'N',
        '0',
        'The budgeted amount per year',
        '',
       '');
 
CREATE TABLE dbo.check_recurring
       (account_code char(6) NOT NULL,
       exp_category1 char(6) NOT NULL,
       exp_category2 char(6) NOT NULL,
       last_posting_date datetime NULL,
       frequency char(1) NOT NULL,
       pay_date1 char(5) NOT NULL,
       pay_date2 char(5) NULL,
       description char(50) NOT NULL,
       trans_amount money NOT NULL,
       memo_fld varchar(40) NULL,
       post_type char(1) NOT NULL,
       tax_exempt char(1) NOT NULL,
       notification_days int NULL);
 
ALTER TABLE check_recurring
       ADD CONSTRAINT ctrec_x PRIMARY KEY
       (account_code,description,trans_amount) ;
 
INSERT INTO dbo.pbcattbl
        (pbt_tnam,
       pbt_tid,
       pbt_ownr,
       pbd_fhgt,
       pbd_fwgt,
       pbd_fitl,
       pbd_funl,
       pbd_fchr,
       pbd_fptc,
       pbd_ffce,
       pbh_fhgt,
       pbh_fwgt,
       pbh_fitl,
       pbh_funl,
       pbh_fchr,
       pbh_fptc,
       pbh_ffce,
       pbl_fhgt,
       pbl_fwgt,
       pbl_fitl,
       pbl_funl,
       pbl_fchr,
       pbl_fptc,
       pbl_ffce,
       pbt_cmnt)
       VALUES
        ( 'check_recurring',
       OBJECT_ID("dbo.check_recurring"),
        'dba',
        -8,
        400,
        'N',
        'N',
        0,
        0,
        '',
        -8,
        700,
        'N',
        'N',
        0,
        0,
        '',
        -8,
        700 ,
        'N',
        'N',
        0,
        0,
        '',
       'This table contains information about recurring activities');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'account_code',
       1,
        'Account:',
       0 ,
        'Acct.
Code',
       0,
       23 ,
        '',
       0 ,
       61 ,
       636 ,
        '',
       'N',
        'spaces',
        'The code that identifies this account',
        'acct_dddw',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'exp_category1',
       2,
        'Exp Category1:',
       0 ,
        'Expense~r~nCategory1',
       0,
       23 ,
        '',
       0 ,
       61 ,
       540 ,
        '',
       'N',
        'spaces',
        'A major category of expense',
        'exp1_dddw',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'exp_category2',
       3,
        'Exp Category2:',
       0 ,
        'Expense~r~nCategory2',
       0,
       23 ,
        '',
       0 ,
       61 ,
       540 ,
        '',
       'N',
        'spaces',
        'A sub-category of expense',
        'exp2_dddw',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'last_posting_date',
       4,
        'Last:',
       23 ,
        'Last~r~nPosting',
       25,
       25 ,
        '',
       0 ,
       61 ,
       266 ,
        '',
       'N',
        'null',
        'The date of the last posting',
        'MM/DD/YY',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'frequency',
       5,
        'Freq:',
       23 ,
        'Frequency',
       25,
       23 ,
        '',
       0 ,
       61 ,
       133 ,
        '',
       'N',
        'M',
        'A frequency of payment: 1/month, bi-monthly, etc.',
        'pay_freq_edit',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'pay_date1',
       6,
        'Day to Pay:',
       23 ,
        'Day to Pay',
       25,
       23 ,
        '',
       0 ,
       61 ,
       133 ,
        '',
       'N',
        '01',
        'The day of the month when payment is due',
        '##',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'pay_date2',
       7,
        'Day:',
       23 ,
        'Day to Pay',
       25,
       23 ,
        '',
       0 ,
       61 ,
       133 ,
        '',
       'N',
        '15',
        'The day of the month when payment is due',
        '##',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'description',
       8,
        'Description:',
       0 ,
        'Description',
       0,
       23 ,
        '',
       0 ,
       61 ,
       659 ,
        '',
       'N',
        'spaces',
        'A description of the item or activity',
        'payees',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'trans_amount',
       9,
        'Amt:',
       0 ,
        'Amount',
       0,
       24 ,
        'currency_display',
       0 ,
       61 ,
       307 ,
        '',
       'N',
        '0',
        'The amount of the payment.',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'memo_fld',
       10,
        'Memo:',
       23 ,
        'Memo',
       25,
       23 ,
        '',
       0 ,
       61 ,
       439 ,
        '',
       'N',
        'null',
        'A memo field',
        '',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'post_type',
       11,
        'Post Type:',
       0 ,
        'Post
Type',
       0,
       23 ,
        '',
       0 ,
       61 ,
       220 ,
        '',
       'N',
        'C',
        'A code identifying the activity as a check, deposit, withdraw or payment',
        'type_ddlb',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'tax_exempt',
       12,
        'Tax Exempt:',
       0 ,
        'Tax~r~nExempt',
       0,
       25 ,
        '',
       26 ,
       61 ,
       133 ,
        '',
       'N',
        'N',
        'Code identifies whether activity is tax exempt.',
        'yes_no',
       '');
 
INSERT INTO dbo.pbcatcol
       (pbc_tnam,
       pbc_tid,
       pbc_ownr,
       pbc_cnam,
       pbc_cid,
       pbc_labl,
       pbc_lpos,
       pbc_hdr,
       pbc_hpos,
       pbc_jtfy,
       pbc_mask,
       pbc_case,
       pbc_hght,
       pbc_wdth,
       pbc_ptrn,
       pbc_bmap,
       pbc_init,
       pbc_cmnt,
       pbc_edit,
       pbc_tag)
        VALUES
        ( 'check_recurring',
        OBJECT_ID("dbo.check_recurring"),
        'dba',
        'notification_days',
       13,
        'Notification Days:',
       23 ,
        'Notification Days',
       25,
       24 ,
        '',
       26 ,
       61 ,
       133 ,
        '',
       'N',
        '0',
        'The number of days before and after to notify that payment is due',
        '##',
       '');

 